---
apt_cache_timeout: 3600
zookeeper:
  version: "3.5.5"
  mirror: "https://artifactory.idfcbank.com/extra-binaries/zookeeper/3.5.5"
  download_dir: "/tmp"
  install_dir: "/home/devopr"
  data_dir: "/home/devopr/var/run/zookeeper/data"
  log_dir: "/var/log/zookeeper"
  server_properties: "zoo.cfg"
tick_time: 2000
init_limit: 10
client_port: 2181
sync_limit: 5
myid: 1
autopurge_snapRetainCount: 3
autopurge_purgeInterval: 1
servers: ""
