
- name: wget java to node
  get_url:
    url: "{{java_mirror}}/{{java_name}}.tar.gz"
    dest: "~/"
    mode: 0644
    force: no
    validate_certs: no
  tags: kafka

- name: Unpack the java tar
  shell: tar -xzvf {{java_name}}.tar.gz
  tags: kafka

- name: Copy java to opt
  shell: sudo cp -rf jdk8u222-b10 /opt/
  tags: kafka

- name: set java home
  shell: echo "export JAVA_HOME=/opt/jdk8u222-b10" >> .bashrc
  tags: kafka

- name: set java path
  shell: echo "export PATH=$PATH:$JAVA_HOME/bin" >> .bashrc
  tags: kafka

- name: refresh source
  shell: source ~/.bashrc
  tags: kafka

- name: Setting internal variable
  set_fact:
          kafka_name: kafka_{{scala_version}}-{{version}}
  tags: kafka

- name: Setting internal variable
  set_fact:
    kafka_dir: "{{ kafka.install_dir }}/{{ kafka_name }}"
  tags: kafka

- name: check if tar has been downloaded
  command: test -f {{ kafka.download_dir }}/{{ kafka_name }}.tgz
  register: kafka_tar_downloaded
  failed_when: kafka_tar_downloaded.rc not in [0, 1]
  changed_when: False
  tags: kafka

- name: Ensure Kafka tar is downloaded
  get_url:
    url: "{{kafka.mirror}}/{{ kafka_name }}.tgz"
    dest: "{{ kafka.download_dir }}/kafka.tgz"
    mode: 0644
    validate_certs: no
    force: no
  tags: kafka

- name: Ensure tar is extracted
  command: tar -zxf {{ kafka.download_dir }}/kafka.tgz chdir={{ kafka.install_dir }}
  tags: kafka

# Config and start Kafka
- name: Copy real config
  template:
    src: kafka-properties.j2
    dest: "{{ kafka_dir }}/config/{{ kafka.server_properties }}"
  tags: kafka

- name: Symlink {{ kafka.install_dir }}/kafka to this version
  shell: ln -s {{ kafka_name }} kafka chdir={{ kafka.install_dir }} creates={{ kafka.install_dir }}/kafka
  tags: kafka

# Ensure that the zookeeper is running before kicking kafka
- name: Lets wait to see if we have Port {{zk_client_port}} is avialable.
  wait_for:
    host: "{{ groups['zookeepers'][0] }}"
    port: "{{ zk_client_port }}"
    delay: 5
    timeout: 50
  tags: kafka

- name: Install the Kafka service handler
  shell: /home/devopr/{{ kafka_name }}/bin/kafka-server-start.sh /home/devopr/{{ kafka_name }}/config/server.properties
  notify: start kafka
  tags: kafka
