apt_cache_timeout: 3600
kafka:
  version: "2.4.0"
  scala_version: "2.11"
  mirror: "https://artifactory.idfcbank.com/extra-binaries/kafka_2.4.0"
  download_dir: "/tmp"
  install_dir: "/home/devopr"
  data_dir: "/home/devopr/kafka/run/kafka/data"
  server_properties: "real-server.properties"

# This does not have to be every Zookeeper host, but the more the better
# by default, we assume this is run at the same time as Zookeeper provisioning
zk_hosts: "{{ groups['zookeepers'] }}" # This does not have to be every Zookeeper host
zk_client_port: 2181
installed_java_version: "java-7-oracle"
